version: "3"
services:
    backend:
    image: makut/ht-backend:latest
        container_name: backend
        networks:
            - app-network
        env_file:
            - secrets.env
    frontend:
        image: makut/ht-frontend:latest
        container_name: frontend
        networks:
            - app-network
    nginx:
        build: ./nginx
        networks:
            - app-network
        ports:
            - "80:80"

networks:
    app-network:
        driver: bridge
